# Generated by Django 6.0.3 on 2026-03-03 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('electrical', 'Electrical'), ('plumbing', 'Plumbing'), ('internet', 'Internet'), ('hvac', 'Air Conditioning'), ('furniture', 'Furniture / Equipment'), ('security', 'Security'), ('cleanliness', 'Cleanliness'), ('other', 'Other')], default='other', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('bld', models.CharField(max_length=50)),
                ('flr', models.CharField(max_length=50)),
                ('rm', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('open', 'Open'), ('progress', 'In Progress'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
