# Generated by Django 6.0.3 on 2026-03-03 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Issue', '0002_issue_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('progress', 'In Progress'), ('hold', 'On Hold'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
