# Generated by Django 6.0.3 on 2026-03-09 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Issue', '0003_issue_rejection_reason_alter_issue_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='in_progress_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
