# Generated by Django 6.0.3 on 2026-03-12 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Issue', '0004_issue_in_progress_at_issue_resolved_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='issue_images/'),
        ),
    ]
